@startsalt
{

  

  // Tela: Gerar Relatório //
  {T "Gerar Relatório"
    [Período: | 01/03/2024 ▾ to 31/03/2024 ▾]
    [Métricas:]
    [ (✔) Vendas por dia  ]
    [ (✔) Produtos mais vendidos ]
    [ ( ) Ticket médio    ]
    [Formato: | (✔) PDF   ( ) Excel ]
    [ [Gerar Relatório] ]
  }
}
@endsalt