site_name: PFE_25.1_8001
theme:
  name: united
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - html
    - css
    - javascript
plugins:
  - open-in-new-tab
repo_url: "https://github.com/jonh-carvalho/PFE_25.1_8001"
